language: generic

matrix:
    include:
        - os: linux
          dist: trusty
          sudo: required
          env: LOCAL_SWIFT_BRANCH="swift-4.1-release" LOCAL_SWIFT_VERSION="swift-4.1-RELEASE" DEPLOY="false"
        - os: osx
          osx_image: xcode10
          language: objective-c

install:
  - ./.ci/install.sh

script:
  - ./.ci/test.sh
